workspace:
  base: /go
  path: src/github.com/smalex-als/health-tracker

pipeline:
  backend:
    image: golang
    commands: 
      - go get -u github.com/smalex-als/health-tracker/server
      - go get -u github.com/gin-gonic/gin
      - go get -u google.golang.org/appengine
      - sh .drone.sh
